from backend.models.state import AgentState
from backend.agents.memory import save_memory
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
import os

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", api_key=os.getenv("GEMINI_API_KEY", "dummy"))

async def reflection_node(state: AgentState):
    """
    Evaluates completed work, formats the final message, and saves memory.
    """
    messages = state.get("messages", [])
    user_id = state.get("user_id", "default_user")
    
    command_type = state.get("command_type", "").strip()
    
    context = ""
    if messages and len(messages) > 1:
        # Get the latest message generated by the previous agent node (Study/Productivity/Memory)
        context = messages[-1].content
        
    if command_type == "weekly_review":
        goals = state.get("active_goals", [])
        system_prompt = f"""
        You are the Reflection Agent acting as a strict but encouraging mentor. 
        The user has requested a Weekly AI Review. Their current active goals are: {goals}
        Review the completed task data and context:
        {context}
        
        Generate a strictly valid JSON response containing the following structure EXACTLY:
        {{
          "score": <an integer from 0 to 100 representing productivity health>,
          "review": "<2 sentence analysis of their week>",
          "recommendation": "<1 actionable improvement>"
        }}
        Do NOT wrap the JSON in markdown code blocks. Just output raw JSON.
        """
        response = await llm.ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content="Return the weekly review JSON.")
        ])
        content = response.content.strip()
        # Thoroughly strip markdown blocks
        content = content.replace("```json", "").replace("```", "").strip()
        
        # Save a basic summary for this event
        summary = "User ran the Weekly AI Review."
        await save_memory(user_id=user_id, text=summary, node_type="reflection")
        
        log_entry = {
            "node": "Reflection",
            "message": "Generated structured Weekly AI Review."
        }
        
        return {
            "messages": [SystemMessage(content=content)],
            "reflection_summary": summary,
            "active_node": "Reflection",
            "pipeline_logs": [log_entry]
        }
    
    else:
        system_prompt = f"""
        You are the Reflection Agent. Review the completed task data from the swarm:
        {context}
        
        Synthesize a concise, helpful, and natural final response to the user.
        Simultaneously, generate a 1-sentence summary of what was accomplished to store in long-term memory.
        
        Format your response EXACTLY like this:
        RESPONSE: <your final user-facing response>
        SUMMARY: <your 1-sentence summary for memory>
        """
        
        response = await llm.ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content="Provide the final synthesized summary.")
        ])
        content = response.content.strip()
        
        final_response = "Task completed."
        summary = "System processed a request."
        
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("RESPONSE:"):
                final_response = line.replace("RESPONSE:", "").strip()
            elif line.startswith("SUMMARY:"):
                summary = line.replace("SUMMARY:", "").strip()
                
        # Save the summary to pinecone
        await save_memory(user_id=user_id, text=summary, node_type="reflection")
                
        log_entry = {
            "node": "Reflection",
            "message": "Synthesized final data and committed summary to long-term memory."
        }
        
        return {
            "messages": [SystemMessage(content=final_response)],
            "reflection_summary": summary,
            "active_node": "Reflection",
            "pipeline_logs": [log_entry]
        }
